[package]
name = "totp-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = { version = "3.2.0", features = ["wayland-data-control"] }
base32 = "0.4.0"
crossterm = "0.25.0"
hmac = "0.12.1"
regex = "1.7.0" 
sha1 = "0.10.5"
wl-clipboard-rs = "0.7.0"
